import Head from 'next/head'
import Image from 'next/image';
import Link from 'next/link';
import { useEffect, useState } from 'react';
import axios from 'axios';
import { Container, Row, Col } from 'react-bootstrap';
import styles from '../styles/Auth.module.scss';
import 'bootstrap/dist/css/bootstrap.min.css';
import { useRouter } from 'next/navigation';
import { ToastContainer, toast } from 'react-toastify';
import 'react-toastify/dist/ReactToastify.css';

const auth = () => {

    useEffect(() => {
      sessionStorage.clear()
    }, [])
    


    const [userName, setUserName] = useState('')
    const [password, setPassword] = useState('')
    const [isLoading, setIsLoading] = useState(true);
    
    const router = useRouter();



    const proceedLogin: (e: any)  => void = async (e) => {
        e.preventDefault()
      
       

        if (validate()) {
            if (isLoading === true) {
                toast.info('Loading data...', {
                  position: toast.POSITION.BOTTOM_CENTER,
                });
              }else {
                toast.dismiss();
              }
             
              await axios.get(`/api/register/${userName}`)
                .then((res) => {
                    console.log(res.data[0])
                   
            
                    if (Object.keys(res.data[0]).length===0) {
                        toast.error('Please enter valid username')
                    }else{

                    if (res.data[0].password === password) {
                            toast.success('Login Seccessful')
                            sessionStorage.setItem('userName', userName)
                               router.push('/')
                        } else {
                            toast.error(`Please Enter valid password`)
                        }
                    }       

                }).catch ((error) =>{
                  
                    console.log(error)
                    toast.error('User doses not exist')
                })

                  
        }


    }

    const validate = () => {
        let result = true;
       
        if (userName === '' || userName === null) {
            result = false;
            toast.warning("Please Enter userName")
        } if (password === '' || password === null) {
            result = false;
            toast.warning("Please Enter password")
        }
        return result


    }
    return (
        <>
         <Head>
        <title>Peddle | Login
        </title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
            <ToastContainer theme='colored' />
            <Container fluid>
                <Row>
                    <Col md={4} className={styles.auth} >
                        <h4>SME Better</h4>

                        <div className='--flex-start --dir-column --gap-2 --mt-9' >
                            <h6>Log into your Business Manager</h6>
                            <div className='--flex-start --dir-column --gap-1 --w-100' >
                                <label>username </label>
                                <input
                                    value={userName}
                                    onChange={e => setUserName(e.target.value)}
                                    type="text" placeholder="moses1234" />
                            </div>

                            <div className='--flex-start --dir-column --gap-1 --w-100'>
                                <label>Enter your password</label>
                                <input
                                    value={password}
                                    onChange={e => setPassword(e.target.value)}
                                    type="password" placeholder="Password" />
                            </div>

                            <a className='link' onClick={proceedLogin}>sign in</a>
                            <div className='--tc --w-100'>
                                <p><Link  href={"/register"}><span className={styles.auth_text_small}>Don’t have an account? </span> <span className={styles.auth_text}>Sign Up</span></Link></p>
                                <p className={styles.auth_text}>Forgot password?</p>
                            </div>

                            <p className={styles.auth_goggle}> <Image
                                src="/assets/google.svg"
                                width='10'
                                height='10'
                                alt='google-img'
                            /> Log in with Google </p>

                        </div>
                    </Col>
                    <Col md={8} className={styles.img}>
                        <p>Organize your customer information</p>
                        <Image src="/assets/auth-img.png"
                            width='420'
                            height='350'
                            alt='auth-img'
                        />
                    </Col>
                </Row>
            </Container>
        </>
    )
}

export default auth