import Head from 'next/head'
import Hero from '../components/hero/Hero'
import Features from '../components/features/Features';
import { Container } from 'react-bootstrap';
import 'bootstrap/dist/css/bootstrap.min.css';
import Plans from '../components/plans/Plans';
import Testimonials from '../components/testimonials/Testimonials';
import Footer from '../components/footer/Footer'
import { useEffect } from 'react';
import { useRouter } from 'next/navigation';
import { ToastContainer, toast } from 'react-toastify';
import 'react-toastify/dist/ReactToastify.css';
export default function Home() {

  const router = useRouter();

  useEffect(() => {
   let userName = sessionStorage.getItem('userName');
   if(userName === '' || userName ===null){
    router.push('/auth')
   }
  }, [])
  
  return (
    <>
      <Head>
        <title>Peddle</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <ToastContainer/>
        <Container fluid>
          <Hero />
          <Features />
          <Plans />
          <Testimonials/>
          <Footer/>
        </Container>
      </main>
    </>
  )
}
