'use client';
import Head from 'next/head'
import { Button, Col, Form, Row, Container } from 'react-bootstrap';
import 'bootstrap/dist/css/bootstrap.min.css';
import {useState} from 'react';
import axios from 'axios';
import { useRouter } from 'next/navigation';
import { ToastContainer, toast } from 'react-toastify';
import 'react-toastify/dist/ReactToastify.css';
import Link from 'next/link';


const register = () => {

  const router = useRouter();

  const [id, setId] = useState('')
  const [email, setEmail] = useState('')
  const [password, setPassword] = useState('')
  const [country, setCountry] = useState('')
  const [city, setCity] = useState('')
  const [address, setAddress] = useState('')
  const [isLoading, setIsLoading] = useState(true);

  const isValidate = () =>{
    let isProceed  = true
    let errorMessage = 'Please enter the value in'
    if(id === null || id === ''){
      isProceed = false;
      errorMessage += ' Username'
    }
    if(email === null || email === ''){
      isProceed = false;
      errorMessage += ' email'
    }
    if(password === null || password === ''){
      isProceed = false;
      errorMessage += ' password'
    }
    if(country === null || country === ''){
      isProceed = false;
      errorMessage += ' country'
    }
    if(address === null || address === ''){
      isProceed = false;
      errorMessage += ' address'
    }
    if(!isProceed){
      toast.warning(errorMessage)
    }
    return isProceed
  }

  const handleSubmit: (e: any) => void = async (e) =>{
    e.preventDefault()
    const data = {id, email, password,address, country}
    console.log(data)

    if(isValidate()){
      if (isLoading === true) {
        toast.info('Loading data...', {
          position: toast.POSITION.BOTTOM_CENTER,
        });
      }else {
        toast.dismiss();
      }

      try {
        await axios.post('/api/register',{
          _id:id,
          email:email,
          password: password,
          address:address,
          country: country,
          
        })
        .then((res) =>{
         router.push('/auth')
          console.log(res)
          toast.success('Registration successful')
        }) 
      } catch (error) {
        console.log(error)
        toast.error('server error')
      }finally{
        
      }
    }
  
  }



  return (
    <>
     <Head>
        <title>Peddle | Register</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    <ToastContainer theme='colored'></ToastContainer>
    <Container style={{marginTop:'5rem'}}>
    <Form onSubmit={handleSubmit}>
      <Row className="mb-3">
      <Form.Group as={Col}>
        <Form.Label>Username</Form.Label>
        <Form.Control
        value={id} onChange={e => setId(e.target.value)}
        type="text" placeholder="Enter Username" />
      </Form.Group>
      </Row>
    <Row className="mb-3">
      <Form.Group as={Col}>
        <Form.Label>Email</Form.Label>
        <Form.Control
         value={email} onChange={e => setEmail(e.target.value)}
        type="email" placeholder="Enter email" />
      </Form.Group>

      <Form.Group as={Col}>
        <Form.Label>Password</Form.Label>
        <Form.Control
         value={password} onChange={e => setPassword(e.target.value)}
        type="password" placeholder="Password" />
      </Form.Group>
    </Row>

    <Form.Group className="mb-3" >
      <Form.Label>Address</Form.Label>
      <Form.Control
       value={address} onChange={e => setAddress(e.target.value)}
      placeholder="1234 Main St" />
    </Form.Group>

    <Row className="mb-3">
      <Form.Group as={Col}>
        <Form.Label>Country</Form.Label>
        <Form.Select
           value={country} onChange={e => setCountry(e.target.value)}
        >
          <option>Choose...</option>
          <option>Nigeria</option>
          <option>USA</option>
          <option>Ghana</option>
        </Form.Select>
      </Form.Group>
    </Row>
    <Button variant="primary" type="submit">
      Submit
    </Button>
    
     <Link className='btn btn-danger' href={'/auth'}> Login</Link>
  
  </Form>
  </Container>
  </>
  );
}

export default register;